FROM punksecurity/smbeagle
RUN apt update && apt install python3 python3-pip -y
RUN pip install impacket pytest
RUN mkdir /empty_dir
WORKDIR /tests/
COPY tests/* .
ENTRYPOINT [ "" ]
ENV ROOTDIR "/"
CMD pytest -v -k 'not on_windows'
