name: Build and publish release on new tag
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build windows x64
        run: dotnet publish -c Release --self-contained -r win-x64 -o packages\windows\x64 -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false
      - name: version
        run: echo ::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)
        shell: bash
        id: version
      - name: Install signing tool
        run: dotnet tool install --global AzureSignTool
      - name: Digitally sign executable
        env:
          CERT_APP_SECRET: ${{ secrets.AZUREKEYVAULTCLIENTSECRET }}
          CERT_APP_ID: ${{ secrets.AZUREKEYVAULTAPPLICATIONID }}
          TENANT_ID: ${{ secrets.AZUREKEYVAULTTENANTID }}
          VAULT_URI: ${{ secrets.AZUREKEYVAULTURI }}
        run: azuresigntool sign -kvt "$env:TENANT_ID" -kvu "$env:VAULT_URI" -kvi "$env:CERT_APP_ID" -kvs "$env:CERT_APP_SECRET" -kvc "PunkSecurity-CodeSigningCert-2022" -tr http://timestamp.globalsign.com/tsa/r6advanced1 -v .\packages\windows\x64\SMBeagle.exe
      - name: Create new release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create archive
        run: Compress-Archive -DestinationPath .\win_x64.zip -Path .\packages\windows\x64
      - name: Upload Win x64 binary
        uses: actions/upload-release-asset@v1
        env:
         GITHUB_TOKEN: ${{ github.token }}
        with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: .\win_x64.zip
         asset_name: smbeagle_${{ steps.version.outputs.version }}_win_x64.zip
         asset_content_type: application/zip
