name: Build and upload preview build

on:
  pull_request:
    branches: [ main ]
    types:
      - synchronize
      - opened
      - reopened

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build windows x64
      run: dotnet publish -c Release --self-contained -r win-x64 -o packages\windows\x64 -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false
    - name: Install signing tool
      run: dotnet tool install --global AzureSignTool
    - name: Digitally sign executable
      env:
        CERT_APP_SECRET: ${{ secrets.AZUREKEYVAULTCLIENTSECRET }}
        CERT_APP_ID: ${{ secrets.AZUREKEYVAULTAPPLICATIONID }}
        TENANT_ID: ${{ secrets.AZUREKEYVAULTTENANTID }}
        VAULT_URI: ${{ secrets.AZUREKEYVAULTURI }}
      run: azuresigntool sign -kvt "$env:TENANT_ID" -kvu "$env:VAULT_URI" -kvi "$env:CERT_APP_ID" -kvs "$env:CERT_APP_SECRET" -kvc "PunkSecurity-CodeSigningCert-2022" -tr http://timestamp.globalsign.com/tsa/r6advanced1 -v .\packages\windows\x64\SMBeagle.exe
    - name: Upload windows x64
      uses: actions/upload-artifact@v2
      with:
        name: windows-x64
        path: packages\windows/x64\*
